# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
$mainMod = SUPER
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/decyanim.conf
