decoration {
    rounding = 10            # Bordes redondeados en píxeles

    # Opacidad (Transparencias)
    active_opacity = 0.8     # Opacidad de la ventana enfocada (0.0 a 1.0)
    inactive_opacity = 0.9   # Opacidad de las ventanas en segundo plano

    # Desenfoque (Blur) estilo Cristal Esmerilado
    blur {
        enabled = true
        size = 10
        passes = 5
        new_optimizations = true
    }

    # Sombras
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

animations {
    enabled = true

    # Puedes definir curvas de velocidad (Beziers)
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    # Aplicar las animaciones a las ventanas, difuminados, etc.
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = fade, 1, 7, default
}
