# Atajos de teclado para acciones comunes
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu

# Ventana flotando
bind = $mainMod, V, togglefloating,
bind = SUPER, V, pin,

# Redimensionar la ventana flotante manteniendo SUPER + Click Derecho y arrastrando
bindm = SUPER, mouse:273, resizewindow
bindm = SUPER, mouse:272, movewindow

# Lanzar aplicaciones específicas con atajos personalizados
bind = $mainMod, O, exec, opera-gx
bind = $mainMod, D, exec, discord
bind = $mainMod, P, exec, spotify

# Cambiar el foco entre ventanas usando $mainMod + Flechas
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Mover la ventana activa usando $mainMod + SHIFT + Flechas
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Cambiar al workspace N ($mainMod + Número)
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
# ... así hasta el 0 (que suele mapearse como el 10)

# Mover la ventana activa al workspace N ($mainMod + SHIFT + Número)
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

#Maxmimizar una ventana
bind = $mainMod, W, fullscreen, 1

# Modo nocturno
bind = $mainMod, L, exec,  hyprsunset -t 4000

#Screenshot
bind = $mainMod, F, exec, grim -g "$(slurp)" - | wl-copy
