# Archivo de configuración de monitores para Hyprland
# Ejemplo => monitor = DP-2, 1920x1080@300, 0x0, 1
# Para ver los nombres de los monitores y resoluciones disponibles, usar el comando `hyprctl monitors`